### ISSUE TITLE
Both the x and y coordinates of fixations exceed 1050? 

### ISSUE THREAD

**Issue by ManooshSamiei** [cvlab-stonybrook/Scanpath_Prediction#11]
Hello,

I am wondering what has been the initial size of the display. In the paper it was mentioned that the display size was 1680x1050. However, both x and y coordinates of fixations exceed 1050; for instance look at fixations for image "000000441856.jpg" for task "chair". I am encountering index error, as I cannot map the original fixation coordinates to a 32x20 action grid. For my training set I am using this file: "coco_search18_fixations_TP_train_split1.json " which I downloaded from the website of cocosearch18. I'd really appreciate it if you could give me some guidance on x and y coordinates of the fixations in  "coco_search18_fixations_TP_train_split1.json " file.  

Thank you in advance for your help.

**Comment by ouyangzhibo** [comment]
> coco_search18_fixations_TP_train_split1

@manooshsamiei76 The size of the display is 1680x1050 as stated in the paper. However, there can possibly be fixations that are out of the boundary as our subjects could happen look outside of the display during the gaze data collection experiment. Those fixations are excluded in our experiments, although we did not exclude them in the raw fixation file ("coco_search18_fixations_TP_train_split1.json") as others may not want to exclude them (e.g., one can project those out-of-boundary fixations back to the nearest in-display point along boundary).

**Comment by ManooshSamiei** [comment]
> > coco_search18_fixations_TP_train_split1
> 
> @manooshsamiei76 The size of the display is 1680x1050 as stated in the paper. However, there can possibly be fixations that are out of the boundary as our subjects could happen look outside of the display during the experiment. Those fixations are excluded in our experiments, although we did not exclude them in the raw fixation file ("coco_search18_fixations_TP_train_split1.json") as others may not want to exclude them (e.g., one can project those out-of-boundary fixations back to the nearest in-display point along boundary).

Thank you very much. Is the file you used for training is the one in the shared drived, where DCBs are also located? There are two files in that shared drive namely: "human_scanpaths_TP_trainval_train.json" and "human_scanpaths_TP_trainval_valid.json" .

**Comment by ouyangzhibo** [comment]
> Thank you very much. Is the file you used for training is the one in the shared drived, where DCBs are also located? There are two files in that shared drive namely: "human_scanpaths_TP_trainval_train.json" and "human_scanpaths_TP_trainval_valid.json" .

I recommend you to download from this [link](https://sites.google.com/view/cocosearch/home) as we included two difference splits in the latest release.

**Comment by ManooshSamiei** [comment]
> > Thank you very much. Is the file you used for training is the one in the shared drived, where DCBs are also located? There are two files in that shared drive namely: "human_scanpaths_TP_trainval_train.json" and "human_scanpaths_TP_trainval_valid.json" .
> 
> I recommend you to download from this [link](https://sites.google.com/view/cocosearch/home) as we included two difference splits in the latest release.

Yes, I am now using the splitted dataset from the same link. But as I mentioned earlier, there are some fixations out of the boundary of display. I think I should add a part to the code to ignore these fixations then.

**Comment by ouyangzhibo** [comment]
> > > Thank you very much. Is the file you used for training is the one in the shared drived, where DCBs are also located? There are two files in that shared drive namely: "human_scanpaths_TP_trainval_train.json" and "human_scanpaths_TP_trainval_valid.json" .
> > 
> > 
> > I recommend you to download from this [link](https://sites.google.com/view/cocosearch/home) as we included two difference splits in the latest release.
> 
> Yes, I am now using the splitted dataset from the same link. But as I mentioned earlier, there are some fixations out of the boundary of display. I think I should add a part to the code to ignore these fixations then.

Yes, please feel free to exclude those fixations. Note that I have also put a rescaled version (512x320) with out-of-boundary fixations excluded [here](https://drive.google.com/drive/u/1/folders/1spD2_Eya5S5zOBO3NKILlAjMEC3_gKWc).
