### ISSUE TITLE
dataset cocosearch-18 is not available

### ISSUE THREAD

**Issue by Mikiloo** [cvlab-stonybrook/Scanpath_Prediction#14]

**Comment by Doch88** [comment]
Are you sure? I can download it without any problem.

**Comment by Mikiloo** [comment]
my classmate can download it,maybe my network occurs something,i will retreat the issue,sorry to bother u, thanks .




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cvlab-stonybrook/Scanpath_Prediction"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 下午4:34
收件人:&nbsp;"cvlab-stonybrook/Scanpath_Prediction"<Scanpath_Prediction@noreply.github.com&gt;;
抄送:&nbsp;"miki"<2507421514@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cvlab-stonybrook/Scanpath_Prediction] dataset cocosearch-18 is not available (#14)





 
Are you sure? I can download it without any problem.

**Comment by MarcWong** [comment]
I also can download it. Check your web envs first?

**Comment by ouyangzhibo** [comment]
@Mikiloo I guess you may encounter some problem when downloading the image files using Chrome. You can try again with another browser. It should work fine with Safari and Firefox.

**Comment by Mikiloo** [comment]
thanks, it's bacause of network, i have already solved it.
