### ISSUE TITLE
test dataset

### ISSUE THREAD

**Issue by Mikiloo** [cvlab-stonybrook/Scanpath_Prediction#18]
could you release the test dataset please?

**Comment by ouyangzhibo** [comment]
> could you release the test dataset please?

I am so sorry that the testing data are still not available. But there has been an unexpected delay in setting up the evaluation server with the MIT/Tuebingen team. We will continue to work with them and set up the evaluation server as soon as we can. I am expecting it to be done in the next few weeks. Will update you once we have it. Thank you for your continued patience!

**Comment by Mikiloo** [comment]
Here is the thing,I have done some work on your paper, and I want to use the methods in your paper as a comparative experiment, but I do not have the test set you used. If you cannot make the test set public, could you please send it to me by email? I will only use it as a comparative experiment in my graduation thesis


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cvlab-stonybrook/Scanpath_Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 凌晨1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cvlab-stonybrook/Scanpath_Prediction] test dataset (#18)





  
could you release the test dataset please?
  
I am so sorry that the testing data are still not available. But there has been an unexpected delay in setting up the evaluation server with the MIT/Tuebingen team. We will continue to work with them and set up the evaluation server as soon as we can. I am expecting it to be done in the next few weeks. Will update you once we have it. Thank you for your continued patience!

**Comment by Mikiloo** [comment]
and I another question, this link https://sites.google.com/view/mcs-dataset/home, MCS dataset, I download the dataset,but didn't find the test data.could u please upload the test data?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cvlab-stonybrook/Scanpath_Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 凌晨1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cvlab-stonybrook/Scanpath_Prediction] test dataset (#18)





  
could you release the test dataset please?
  
I am so sorry that the testing data are still not available. But there has been an unexpected delay in setting up the evaluation server with the MIT/Tuebingen team. We will continue to work with them and set up the evaluation server as soon as we can. I am expecting it to be done in the next few weeks. Will update you once we have it. Thank you for your continued patience!

**Comment by ouyangzhibo** [comment]
Hi @Mikiloo, I contacted the owner of the MCS dataset and they agreed to release the testing data. I updated the [dataset website](https://sites.google.com/view/mcs-dataset/home). You can also download them via [this link](https://drive.google.com/file/d/1_8nqqfj56zecf02vRA-YTe6TQKXTBpeV/view?usp=sharing). Hope this helps!

**Comment by ouyangzhibo** [comment]
> Here is the thing,I have done some work on your paper, and I want to use the methods in your paper as a comparative experiment, but I do not have the test set you used. If you cannot make the test set public, could you please send it to me by email? I will only use it as a comparative experiment in my graduation thesis

Sorry that I may not be able to send you the data now as I am not the creator of the dataset. What I can do is to keep pushing them to set up the evaluation server asap. If you need it urgently for your thesis, maybe you could re-split the trainval set to compare your model with others.

**Comment by Mikiloo** [comment]
thats good suggestion,thanks for your reply .



---Original---
From: "Zhibo ***@***.***&gt;
Date: Mon, Apr 12, 2021 23:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cvlab-stonybrook/Scanpath_Prediction] test dataset (#18)




  
Here is the thing,I have done some work on your paper, and I want to use the methods in your paper as a comparative experiment, but I do not have the test set you used. If you cannot make the test set public, could you please send it to me by email? I will only use it as a comparative experiment in my graduation thesis
  
Sorry that I may not be able to send you the data now as I am not the creator of the dataset. What I can do is to keep pushing them to set up the evaluation server asap. If you need it urgently for your thesis, maybe you could re-split the trainval set to compare your model with others.

**Comment by StoyanVenDimitrov** [comment]
Hi, I would like to reproduce your results on the Cocosearch18 test set. Do you have the DCB tensors for it, similar to the train and validation datasets?
