### ISSUE TITLE
Cocosearch18 test set

### ISSUE THREAD

**Issue by StoyanVenDimitrov** [cvlab-stonybrook/Scanpath_Prediction#22]
Hi, I would like to reproduce your results on the Cocosearch18 test set. Do you have the DCB tensors for it, similar to the train and validation datasets, as well as the test set annotations?

**Comment by ouyangzhibo** [comment]
Please find the all DCB tensors and the bounding box annotations (including the test set) at https://drive.google.com/drive/folders/1C2kK4dGgVWZOgplIjleB5WG18X2yBtRw?usp=sharing.

Note: you can use [extract_DCBs_demo.py](https://github.com/cvlab-stonybrook/Scanpath_Prediction/blob/master/extract_DCBs_demo.py) to extract DCB representation and the bounding box annotation can be extracted using [cocoapi](https://github.com/cocodataset/cocoapi).

**Comment by StoyanVenDimitrov** [comment]
Thank you! I guess the test annotations are [here](https://sites.google.com/view/cocosearch/) under COCO-Search18 TP Dataset /Testing Set?

**Comment by ouyangzhibo** [comment]
> Thank you! I guess the test annotations are [here](https://sites.google.com/view/cocosearch/) under COCO-Search18 TP Dataset /Testing Set?

Oh, yes. I thought you mean the bounding box annotations only. I am closing this issue, but feel free to reopen it if there are any further questions.

**Comment by StoyanVenDimitrov** [comment]
Thank you, I was able to generate test trajectories. But please refer to my comments on #16 . I was not able to reproduce your test results
