### ISSUE TITLE
Fixation duration definition

### ISSUE THREAD

**Issue by bsureshkrishna** [cvlab-stonybrook/Scanpath_Prediction#23]
Hello,

Thank you very much for making these datasets available !

We are interested in looking into fixation durations in these 2 datasets.

Sorry if I have missed it, but I could not figure out how fixation start and end was defined: was it based on the termination of the preceding saccade (or start of trial) and start of the following saccade ? That is, saccade duration was not included in the fixation duration ?

We were also curious about how saccades were detected, and how small/micro-saccades were handled.

Would it be at all possible to get access to the actual eye-traces from which the fixations were calculated ?

Thanks and best, Suresh

**Comment by ouyangzhibo** [comment]
I am forwarding your question to our colleague (Yupei Chen yupei.chen@ski.org ). She should be able to help with your question. At the mean time, you're welcomed to read our dataset paper https://www.nature.com/articles/s41598-021-87715-9, which contains more details of how the dataset was collected.

**Comment by bsureshkrishna** [comment]
@ouyangzhibo Thank you.. yes, i have seen the paper, and did not find the info in the paper or the supplementary materials.. but perhaps it is indeed there and i missed it.

**Comment by yupeichen** [comment]
@bsureshkrishna Thank you for your interest in our dataset! The fixation duration was from the start of the current fixation (end of the previous saccade) to the end of the current fixation. So yes, saccade duration was not included in the fixation duration. The fixation and saccade data was obtained by DataViewer (a fixation/saccade extraction software developed by Eyelink). DataViewer handles microsacces in its algorithms and we did not change their settings. Regarding the eye-traces, do you mean the raw .edf files from Eyelink?

**Comment by bsureshkrishna** [comment]
Thank you so much for the response ! 

Regarding DataViewer, was the MergeFixation parameter checked: https://www.sr-support.com/showthread.php?tid=146

And yes, by eye-traces, I meant the raw EDFs, so that we could run our own alternative saccade algorithms on the raw data.. 

Thanks again !

**Comment by bsureshkrishna** [comment]
ps. Also, it seems that DataViewer uses the saccades detected by the online algorithm ? And for that, it seems there can be at least two configurations:

"The EyeLink online parser uses a "saccade picking" approach, in which instantaneous velocity and acceleration thresholds to determine the onset and offset of saccades; samples above threshold are determined to be in saccade, and samples below threshold are determined to be in fixation. The standard parser setting uses velocity and acceleration thresholds of 30°/s and 8000°/s^2, respectively. So the onset of a fixation is determined by the offset of the previous saccade, and the offset of a fixation is determined by the onset of the subsequent saccade." from - https://www.sr-support.com/thread-212.html

Also, the manual says (4.3.9): The complete set of commands for the most useful tracker configurations is given below. The cognitive configuration is conservative, is less sensitive to noise and ignores most saccades smaller than 0.6°. The psychophysical configuration is useful for neurological and smooth-pursuit research, and reports very small saccades. It also better estimates saccade durations and average velocities.

Cognitive Configuration:
recording_parse_type = GAZE
saccade_velocity_threshold = 30
saccade_acceleration_threshold = 8000
saccade_motion_threshold = 0.1
saccade_pursuit_fixup = 60
fixation_update_interval = 0

Psychophysical configuration:
recording_parse_type = GAZE
saccade_velocity_threshold = 22
saccade_acceleration_threshold = 3800
saccade_motion_threshold = 0.0
saccade_pursuit_fixup = 60
fixation_update_interval = 0

**Comment by ouyangzhibo** [comment]
Solved via email.
