### ISSUE TITLE
Qusetion about dataset?

### ISSUE THREAD

**Issue by HectorTo** [cvlab-stonybrook/Scanpath_Prediction#26]
I hope this finds you well.
Where can I get bbox_annos.npy in the dataset? Could you give me a direct link? Thanks a lot!

**Comment by ouyangzhibo** [comment]
You can find it here https://drive.google.com/corp/drive/folders/1spD2_Eya5S5zOBO3NKILlAjMEC3_gKWc.

**Comment by HectorTo** [comment]
thanks a lot！
