### ISSUE TITLE
Multiple instances of the target

### ISSUE THREAD

**Issue by ghost** [cvlab-stonybrook/Scanpath_Prediction#4]
@ouyangzhibo 
in you paper you stated:
 "The image should include one and only one instance of the target."

- In my case, i have multiple "text-lines" as input target, which i want to predict their Reading-Order.
How should i solve it? Should i label each "text-line" as: line1, line2, line3, etc...
Or can i input multiple instances of the same target "text-line"? 
do you have any suggestions?
- There is only 1 entry in "bbox", what about multiple occurrences of the same object in one image?

**Comment by ghost** [comment]
@ouyangzhibo

**Comment by ouyangzhibo** [comment]
> @ouyangzhibo
> in you paper you stated:
> "The image should include one and only one instance of the target."
> 
> * In my case, i have multiple "text-lines" as input target, which i want to predict their Reading-Order.
>   How should i solve it? Should i label each "text-line" as: line1, line2, line3, etc...
>   Or can i input multiple instances of the same target "text-line"?
>   do you have any suggestions?
> * There is only 1 entry in "bbox", what about multiple occurrences of the same object in one image?

@deepseek The images in our dataset are purposely selected such that every image contains only one target object. This is to simplify the search behaviors for better analysis. I am not sure whether your text-reading task can be regarded as  search task or now. But the overall IRL framework can still be applied no matter how many targets are there. However, the proposed DCB state representation is not feasible in your case.
