### ISSUE TITLE
Maximum number of steps (fixations)

### ISSUE THREAD

**Issue by ManooshSamiei** [cvlab-stonybrook/Scanpath_Prediction#9]
Hello, 

I am wondering why you increase the maximum eye trajectory length by one, changing it from 6 to 7, while you calculate the cdf, in the below code:  

    def compute_search_cdf(scanpaths, annos, max_step, return_by_task=False):
    # compute search CDF
    task_names = np.unique([traj['task'] for traj in scanpaths])
    num_steps = get_num_steps(scanpaths, annos, task_names)
    cdf_tasks = get_mean_cdf(num_steps, task_names, max_step + 1)
    if return_by_task:
        return dict(zip(task_names, cdf_tasks))
    else:
        mean_cdf = np.mean(cdf_tasks, axis=0)
        std_cdf = np.std(cdf_tasks, axis=0)
        return mean_cdf, std_cdf

its written 

    cdf_tasks = get_mean_cdf(num_steps, task_names, max_step + 1)

which adds 1 to the max_step.

**Comment by ouyangzhibo** [comment]
> Hello,
> 
> I am wondering why you increase the maximum eye trajectory length by one, changing it from 6 to 7, while you calculate the cdf, in the below code:
> 
> ```
> def compute_search_cdf(scanpaths, annos, max_step, return_by_task=False):
> # compute search CDF
> task_names = np.unique([traj['task'] for traj in scanpaths])
> num_steps = get_num_steps(scanpaths, annos, task_names)
> cdf_tasks = get_mean_cdf(num_steps, task_names, max_step + 1)
> if return_by_task:
>     return dict(zip(task_names, cdf_tasks))
> else:
>     mean_cdf = np.mean(cdf_tasks, axis=0)
>     std_cdf = np.std(cdf_tasks, axis=0)
>     return mean_cdf, std_cdf
> ```
> 
> its written
> 
> ```
> cdf_tasks = get_mean_cdf(num_steps, task_names, max_step + 1)
> ```
> 
> which adds 1 to the max_step.

That't due to the fact that the initial fixations starts at the center and we wanted to see the results for 6 extra steps (excluding the initial one), so we add one step after the `max_step` in one of our experiments. You can remove the +1 here if it is not desired in your case.

**Comment by ManooshSamiei** [comment]
I see.. Thank you very much. I first thought when you mentioned you used 6 fixations in the paper, you are including the initial fixation as well.
